[2022-09-03 13:51:15,680] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_airflow.Extraction scheduled__2022-09-03T02:40:00+00:00 [queued]>
[2022-09-03 13:51:15,683] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_airflow.Extraction scheduled__2022-09-03T02:40:00+00:00 [queued]>
[2022-09-03 13:51:15,683] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-03 13:51:15,683] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-03 13:51:15,683] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-03 13:51:15,688] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): Extraction> on 2022-09-03 02:40:00+00:00
[2022-09-03 13:51:15,695] {standard_task_runner.py:52} INFO - Started process 40851 to run task
[2022-09-03 13:51:15,699] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_airflow', 'Extraction', 'scheduled__2022-09-03T02:40:00+00:00', '--job-id', '587', '--raw', '--subdir', 'DAGS_FOLDER/etl_airflowv2.py', '--cfg-path', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmpkoj0elfk', '--error-file', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmp425n2uuk']
[2022-09-03 13:51:15,701] {standard_task_runner.py:77} INFO - Job 587: Subtask Extraction
[2022-09-03 13:51:15,724] {logging_mixin.py:109} INFO - Running <TaskInstance: etl_airflow.Extraction scheduled__2022-09-03T02:40:00+00:00 [running]> on host Jonathans-MacBook-Pro.local
[2022-09-03 13:51:15,746] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jonathan.dejesus.azor@gmail.com
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=etl_airflow
AIRFLOW_CTX_TASK_ID=Extraction
AIRFLOW_CTX_EXECUTION_DATE=2022-09-03T02:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-03T02:40:00+00:00
[2022-09-03 13:51:17,068] {logging_mixin.py:109} INFO -      incident_report_number  ... rep_time
0               20222391738  ...     2353
1               20222391646  ...     2346
2               20222391707  ...       27
3               20222391708  ...     2340
4               20222391682  ...       37
..                      ...  ...      ...
195             20222381037  ...     1626
196             20222381066  ...     1623
197             20222381057  ...     1601
198             20222380989  ...     1559
199             20222381059  ...     1630

[200 rows x 9 columns]
[2022-09-03 13:51:17,069] {python.py:175} INFO - Done. Returned value was:      incident_report_number  ... rep_time
0               20222391738  ...     2353
1               20222391646  ...     2346
2               20222391707  ...       27
3               20222391708  ...     2340
4               20222391682  ...       37
..                      ...  ...      ...
195             20222381037  ...     1626
196             20222381066  ...     1623
197             20222381057  ...     1601
198             20222380989  ...     1559
199             20222381059  ...     1630

[200 rows x 9 columns]
[2022-09-03 13:51:17,082] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=etl_airflow, task_id=Extraction, execution_date=20220903T024000, start_date=20220903T185115, end_date=20220903T185117
[2022-09-03 13:51:17,106] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-03 13:51:17,120] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-03 14:00:28,116] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_airflow.Extraction scheduled__2022-09-03T02:40:00+00:00 [queued]>
[2022-09-03 14:00:28,119] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_airflow.Extraction scheduled__2022-09-03T02:40:00+00:00 [queued]>
[2022-09-03 14:00:28,119] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-03 14:00:28,119] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-03 14:00:28,119] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-03 14:00:28,124] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): Extraction> on 2022-09-03 02:40:00+00:00
[2022-09-03 14:00:28,130] {standard_task_runner.py:52} INFO - Started process 41207 to run task
[2022-09-03 14:00:28,135] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_airflow', 'Extraction', 'scheduled__2022-09-03T02:40:00+00:00', '--job-id', '634', '--raw', '--subdir', 'DAGS_FOLDER/etl_airflowv2.py', '--cfg-path', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmpjru50aiv', '--error-file', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmptm43q2vc']
[2022-09-03 14:00:28,136] {standard_task_runner.py:77} INFO - Job 634: Subtask Extraction
[2022-09-03 14:00:28,161] {logging_mixin.py:109} INFO - Running <TaskInstance: etl_airflow.Extraction scheduled__2022-09-03T02:40:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-09-03 14:00:28,184] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jonathan.dejesus.azor@gmail.com
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=etl_airflow
AIRFLOW_CTX_TASK_ID=Extraction
AIRFLOW_CTX_EXECUTION_DATE=2022-09-03T02:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-03T02:40:00+00:00
[2022-09-03 14:00:29,820] {logging_mixin.py:109} INFO -      incident_report_number  ... rep_time
0               20222391738  ...     2353
1               20222391646  ...     2346
2               20222391708  ...     2340
3               20222391707  ...       27
4               20222391682  ...       37
..                      ...  ...      ...
195             20222381037  ...     1626
196             20222381066  ...     1623
197             20222381057  ...     1601
198             20222380989  ...     1559
199             20222381059  ...     1630

[200 rows x 9 columns]
[2022-09-03 14:00:33,025] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2022-09-03 14:00:36,029] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2022-09-03 14:00:36,030] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2022-09-03 14:00:36,031] {_default.py:290} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2022-09-03 14:00:40,354] {logging_mixin.py:109} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2022-09-03 14:00:40,355] {gbq.py:604} INFO - 200 out of 200 rows loaded.
[2022-09-03 14:00:40,356] {logging_mixin.py:109} WARNING - 100%|##########| 1/1 [00:00<00:00, 2763.05it/s]
[2022-09-03 14:00:40,356] {logging_mixin.py:109} WARNING - 
[2022-09-03 14:00:40,356] {logging_mixin.py:109} INFO - Staging table completed successfully
[2022-09-03 14:00:40,356] {python.py:175} INFO - Done. Returned value was: None
[2022-09-03 14:00:40,364] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=etl_airflow, task_id=Extraction, execution_date=20220903T024000, start_date=20220903T190028, end_date=20220903T190040
[2022-09-03 14:00:40,389] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-03 14:00:40,403] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
