[2022-09-02 12:22:02,614] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_crime.Extraction scheduled__2022-08-28T02:20:00+00:00 [queued]>
[2022-09-02 12:22:02,629] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_crime.Extraction scheduled__2022-08-28T02:20:00+00:00 [queued]>
[2022-09-02 12:22:02,629] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 12:22:02,629] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-02 12:22:02,629] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 12:22:02,633] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): Extraction> on 2022-08-28 02:20:00+00:00
[2022-09-02 12:22:02,640] {standard_task_runner.py:52} INFO - Started process 36568 to run task
[2022-09-02 12:22:02,645] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_crime', 'Extraction', 'scheduled__2022-08-28T02:20:00+00:00', '--job-id', '553', '--raw', '--subdir', 'DAGS_FOLDER/etl_bigquery.py', '--cfg-path', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmp94qozyy9', '--error-file', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmpoevletpa']
[2022-09-02 12:22:02,646] {standard_task_runner.py:77} INFO - Job 553: Subtask Extraction
[2022-09-02 12:22:02,673] {logging_mixin.py:109} INFO - Running <TaskInstance: etl_crime.Extraction scheduled__2022-08-28T02:20:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-09-02 12:22:02,716] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jonathan.dejesus.azor@gmail.com
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=etl_crime
AIRFLOW_CTX_TASK_ID=Extraction
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T02:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-28T02:20:00+00:00
[2022-09-02 12:22:05,580] {logging_mixin.py:109} INFO -      incident_report_number  ... rep_time
0               20222391738  ...     2353
1               20222391646  ...     2346
2               20222391707  ...       27
3               20222391708  ...     2340
4               20222391682  ...       37
..                      ...  ...      ...
195             20222381037  ...     1626
196             20222381066  ...     1623
197             20222381057  ...     1601
198             20222380989  ...     1559
199             20222381059  ...     1630

[200 rows x 9 columns]
[2022-09-02 12:22:08,793] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
[2022-09-02 12:22:11,796] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
[2022-09-02 12:22:11,797] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2022-09-02 12:22:11,798] {_default.py:290} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2022-09-02 12:22:17,696] {logging_mixin.py:109} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2022-09-02 12:22:17,697] {gbq.py:604} INFO - 200 out of 200 rows loaded.
[2022-09-02 12:22:17,697] {logging_mixin.py:109} WARNING - 100%|##########| 1/1 [00:00<00:00, 4424.37it/s]
[2022-09-02 12:22:17,697] {logging_mixin.py:109} WARNING - 
[2022-09-02 12:22:17,697] {logging_mixin.py:109} INFO - Staging table completed successfully
[2022-09-02 12:22:17,698] {python.py:175} INFO - Done. Returned value was: None
[2022-09-02 12:22:17,705] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=etl_crime, task_id=Extraction, execution_date=20220828T022000, start_date=20220902T172202, end_date=20220902T172217
[2022-09-02 12:22:17,730] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-02 12:22:17,742] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
