[2022-09-02 12:34:55,683] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_crime.Transform scheduled__2022-09-02T01:00:00+00:00 [queued]>
[2022-09-02 12:34:55,686] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: etl_crime.Transform scheduled__2022-09-02T01:00:00+00:00 [queued]>
[2022-09-02 12:34:55,686] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 12:34:55,686] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-09-02 12:34:55,686] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-02 12:34:55,690] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): Transform> on 2022-09-02 01:00:00+00:00
[2022-09-02 12:34:55,697] {standard_task_runner.py:52} INFO - Started process 36774 to run task
[2022-09-02 12:34:55,702] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_crime', 'Transform', 'scheduled__2022-09-02T01:00:00+00:00', '--job-id', '567', '--raw', '--subdir', 'DAGS_FOLDER/etl_bigquery.py', '--cfg-path', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmp0435e0pd', '--error-file', '/var/folders/35/pzst1sv14yld_nkt23lk_vmr0000gn/T/tmpyafkpxv8']
[2022-09-02 12:34:55,703] {standard_task_runner.py:77} INFO - Job 567: Subtask Transform
[2022-09-02 12:34:55,726] {logging_mixin.py:109} INFO - Running <TaskInstance: etl_crime.Transform scheduled__2022-09-02T01:00:00+00:00 [running]> on host 1.0.0.127.in-addr.arpa
[2022-09-02 12:34:55,749] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jonathan.dejesus.azor@gmail.com
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=etl_crime
AIRFLOW_CTX_TASK_ID=Transform
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T01:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-02T01:00:00+00:00
[2022-09-02 12:34:55,961] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: [Errno 64] Host is down
[2022-09-02 12:34:55,962] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: [Errno 64] Host is down
[2022-09-02 12:34:55,962] {_metadata.py:99} WARNING - Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
[2022-09-02 12:34:55,962] {_default.py:290} WARNING - Authentication failed using Compute Engine authentication due to unavailable metadata server.
[2022-09-02 12:34:57,106] {logging_mixin.py:109} WARNING - Downloading:   0%|          | 0/200 [00:00<?, ?rows/s]
[2022-09-02 12:34:57,293] {logging_mixin.py:109} WARNING - Downloading: 100%|##########| 200/200 [00:00<00:00, 1078.15rows/s]
[2022-09-02 12:34:57,293] {logging_mixin.py:109} WARNING - Downloading: 100%|##########| 200/200 [00:00<00:00, 1073.61rows/s]
[2022-09-02 12:34:57,293] {logging_mixin.py:109} WARNING - 
[2022-09-02 12:34:57,300] {logging_mixin.py:109} INFO - Staging table extraction successfully completed
[2022-09-02 12:34:57,309] {logging_mixin.py:109} INFO -      incident_report_number  ... rep_time
0               20222381575  ...     2129
1               20222381479  ...     1935
2               20222381858  ...     2337
3               20222381688  ...     2201
4               20222381348  ...     1830
..                      ...  ...      ...
195             20222390765  ...     1208
196             20222391622  ...        7
197             20222391707  ...       27
198             20222391682  ...       37
199             20222391561  ...       10

[200 rows x 9 columns]
[2022-09-02 12:34:57,344] {logging_mixin.py:109} INFO - Index(['incident_report_number', 'crime_type', 'location_type', 'address',
       'zip_code', 'occurred_date', 'ocurred_time', 'reported_date',
       'reported_time', 'new_occurred_time', 'std_time_new_occurred_time',
       'new_reported_time', 'std_time_new_reported_time'],
      dtype='object')
[2022-09-02 12:34:57,345] {logging_mixin.py:109} INFO - Index(['incident_report_number', 'crime_type', 'location_type', 'address',
       'zip_code', 'occurred_date', 'ocurred_time', 'reported_date',
       'reported_time', 'std_time_new_occurred_time',
       'std_time_new_reported_time'],
      dtype='object')
[2022-09-02 12:35:03,006] {logging_mixin.py:109} WARNING -   0%|          | 0/1 [00:00<?, ?it/s]
[2022-09-02 12:35:03,008] {gbq.py:604} INFO - 200 out of 200 rows loaded.
[2022-09-02 12:35:03,009] {logging_mixin.py:109} WARNING - 100%|##########| 1/1 [00:00<00:00, 1122.07it/s]
[2022-09-02 12:35:03,009] {logging_mixin.py:109} WARNING - 
[2022-09-02 12:35:03,010] {logging_mixin.py:109} INFO - Staging 2 table completed successfully
[2022-09-02 12:35:03,010] {python.py:175} INFO - Done. Returned value was: None
[2022-09-02 12:35:03,029] {taskinstance.py:1267} INFO - Marking task as SUCCESS. dag_id=etl_crime, task_id=Transform, execution_date=20220902T010000, start_date=20220902T173455, end_date=20220902T173503
[2022-09-02 12:35:03,053] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-02 12:35:03,063] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
